const images = {
  logo: '/assets/images/landing-page/logo.svg',
  heroBackground:'/assets/images/landing-page/wave.png',
  heroImage:'/assets/images/landing-page/hero_image.svg',
  commitmentIcon:'/assets/images/landing-page/commitment_icon.svg',
  excellenceIcon:'/assets/images/landing-page/excellence_icon.svg',
  integrityIcon:'/assets/images/landing-page/integrity_icon.svg',
  respectIcon:'/assets/images/landing-page/respect_icon.svg',
  happyNurseandManWheelchair:'/assets/images/landing-page/happy-nurse-man-wheelchair.png',
  ladiesDonating:'/assets/images/landing-page/ladies_donating.png',
  ladyandLadyWheelchair:'/assets/images/landing-page/lady_lady_wheelchair.png',
  manDrinkCoffee:'/assets/images/landing-page/man-drink-coffee.png',
  prayingMan:'/assets/images/landing-page/man-praying.png',
  nurseCheckingMan:'/assets/images/landing-page/nurse-checking-man.png',
  nurseSittingWithOldManWoman:'/assets/images/landing-page/nurse-old-man-woman-sofa.png',
  oldageHome:'/assets/images/landing-page/oldagehome.png',
  oldManWithCaretaker:'/assets/images/landing-page/oldman_caretaker.png',
  patientWithDoctor:'/assets/images/landing-page/patient-with-kind-doctor.png',
  socialworkers:'/assets/images/landing-page/socialworkers-helping-disabled-man.png',
  womanCaregiver:'/assets/images/landing-page/woman_caregiver_outdoor.png',
  doctorCaringWoman:'/assets/images/landing-page/doctor-taking-care-senior-woman.png',
  seniorWomanSittingBedroom:'/assets/images/landing-page/senior-woman-sitting-bedroom.png',
  joyfulOldLady:'/assets/images/landing-page/joyful-old-lady-sitting-couch.png',
  ladyDoctor1:'/assets/images/landing-page/lady_doctor_1.png',
  ladyDoctor2:'/assets/images/landing-page/lady_doctor_2.png',
  maleDoctor1:'/assets/images/landing-page/male_doctor_1.png',
  holdingHands:'/assets/images/landing-page/holding_hands.png',
  staffs1:'/assets/images/landing-page/staffs1.png',
  staffs2:'/assets/images/landing-page/staffs2.png',
  ladyDoctorRaindrop:'/assets/images/landing-page/lady_doctor_raindrop.png',
  womenInWheelchair:'/assets/images/landing-page/womenInWheelchair.svg',
  logoutIcon:'/assets/images/logout_icon.svg',
  manLogin:'/assets/images/landing-page/man_login.svg',
  seniorsEatingDinner:'/assets/images/landing-page/Sr_men_women_eating_dinner.svg',
  seniorsWatchingTV:'/assets/images/landing-page/senior_people_watching_tv.svg',
  seniorsPlayingChess:'/assets/images/landing-page/senior_people_playing_chess.svg',
  DrCheckingSrWomen:'/assets/images/landing-page/DrCheckingSrWomen.svg',
  maleHealthVisitor:'/assets/images/landing-page/male_health_visitor.svg',
  gatheringSrPeople:'/assets/images/landing-page/gathering_senior_people.svg',
  femaleHealthVisitor:'/assets/images/landing-page/female-nurse-taking-care-elderly-person.svg',
  nurseFeedingSrMan:'/assets/images/landing-page/nurse_feeding_Sr_man.svg',
  drGivingPills:'/assets/images/landing-page/doctor_giving_pills.svg',
  oldmanReadingBook:'/assets/images/landing-page/oldman_reading_book.svg'
  // Add more image constants as needed
};

export default images;
